# Generated by Django 6.0.3 on 2026-03-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
    ]
